name: Build and Publish NuGet Packages

on:
    push:
        branches:
            - master

jobs:
    build-and-publish:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup .NET
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore

            # - name: Run tests
            #   run: dotnet test --no-restore

            - name: Build Snakeskin
              run: dotnet build src/Snakeskin/Snakeskin.csproj --configuration Release --no-restore

            - name: Publish Snakeskin to NuGet
              run: dotnet nuget push src/Snakeskin/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
              if: success()

            - name: Build Snakeskin.EntityFrameworkCore
              run: dotnet build src/Snakeskin.EntityFrameworkCore/Snakeskin.EntityFrameworkCore.csproj --configuration Release --no-restore
              if: success()

            - name: Publish Snakeskin.EntityFrameworkCore to NuGet
              run: dotnet nuget push src/Snakeskin.EntityFrameworkCore/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
              if: success()
